version: '3'

services: 
    laravel-app:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx
        networks: 
            - app-network
        
    mysql-app:
        image: mysql:5.7.22
        ports: 
            - "3333:3306"
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: redesocial
            MYSQL_ROOT_PASSWORD: redesocial
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge